name: Deploy Application

on:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup node.js environment
        uses: actions/setup-node@v2.1.2

      - name: Npm install & npm build
        run: |
          npm install
          npm run build

      - name: Upload
        uses: appleboy/scp-action@master
        with:
          host: ${{ matrix.server.ip }}
          username: ${{ matrix.server.username }}
          key: ${{ secrets.ROYALTY_SERVER_SSH }}
          port: ${{ matrix.server.port }}
          SOURCE_DIR: 'dist'
          target: ${{ matrix.server.path }}/frontend
